{{- if .Values.redis.enabled -}}
{{ $fullname := printf "%s-redis" .Release.Name | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ $fullname }}
          image: {{ .Values.redis.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 5432
              protocol: TCP
          {{- if .Values.redis.resources }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            exec:
              command: ["sh", "-c", "redis-cli ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["sh", "-c", "redis-cli ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ $fullname }}-volume
{{- end -}}
