{{ $fullname := printf "%s-django" .Release.Name | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ .Values.django.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      {{- with .Values.django.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $fullname }}
          image: {{ include "application.image" . }}
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ $fullname }}-secrets
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.django.resources }}
          resources:
            {{- toYaml .Values.django.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.django.medias.enabled }}
          volumeMounts:
            - name: medias
              mountPath: {{ .Values.django.medias.mountPath }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /api/exploit/alive/
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/exploit/alive/
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/exploit/alive/
              port: http
            periodSeconds: 10
      {{- if .Values.django.medias.enabled }}
      volumes:
        - name: medias
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-medias-volume
      {{- end }}
