apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-django-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.django.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  # PostgreSQL
  {{- if .Values.postgresql.enabled }}
  {{- $postgres_service := printf "%s-postgresql-service" .Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $postgres_hostname := printf "%s.%s.svc.cluster.local" $postgres_service .Release.Namespace }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s:5432/%s" .Values.postgresql.username .Values.postgresql.password $postgres_hostname .Values.postgresql.database | b64enc | quote }}
  {{- end -}}
  # RabbitMQ
  {{- if .Values.rabbitmq.enabled }}
  {{- $rabbitmq_service := printf "%s-rabbitmq-service" .Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $rabbitmq_hostname := printf "%s.%s.svc.cluster.local" $rabbitmq_service .Release.Namespace }}
  CELERY_BROKER_URL: {{ printf "pyamqp://%s:%s@%s/%s" .Values.rabbitmq.username .Values.rabbitmq.password $rabbitmq_hostname .Values.rabbitmq.vhost | b64enc | quote }}
  {{- end -}}
  # Redis
  {{- if .Values.redis.enabled }}
  {{- $redis_service := printf "%s-redis-service" .Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $redis_hostname := printf "%s.%s.svc.cluster.local" $redis_service .Release.Namespace }}
  CACHE_URL: {{ printf "redis://%s:6379/0" $redis_hostname | b64enc | quote }}
  {{- end -}}
