{{- if .Values.postgresql.enabled -}}
{{ $fullname := printf "%s-postgresql" .Release.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    app: {{ $fullname }}
{{- end -}}
