{{- if .Values.rabbitmq.enabled -}}
{{ $fullname := printf "%s-rabbitmq" .Release.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | b64enc | quote }}
  RABBITMQ_DEFAULT_VHOST: {{ .Values.rabbitmq.vhost | b64enc | quote }}
{{- end -}}
